### ISSUE TITLE
Easy installer for Windows/Linux?

### ISSUE THREAD

**Issue by davethecipo** [Jacotsu/polibeepsync#28]
The previous experiments with py2exe/py2app/cx_Freeze failed, I could retry though. 

A difficult installation process cuts out most of the intended audience.

**Comment by davethecipo** [comment]
The problem was that cacert.pem was missing. Solved (for Windows) with 9b4b263abe1c720d58773af9f34cf3d25c9a01e1.

The remaining problem is self-updating, which can be accomplished via Esky.

**Comment by davethecipo** [comment]
At the moment there's a bug in esky which requires a workaround:

1) use python 3.3
2) manually copy cacert.pem to the main output folder

For linux, using esky/cx_freeze is not a viable option because of glibc. It's better to opensuse build service to build the package in the specific format required by the distribution.

**Comment by Jacotsu** [comment]
Solved with PPA and stdeb
