### ISSUE TITLE
I found the cli script that uses the BeeP API

### ISSUE THREAD

**Issue by davethecipo** [Jacotsu/polibeepsync#38]
Hello @Jacotsu, 
I have good news, I found the code of the CLI script. It was called beepbox. The creator is @poliscript, sadly it doesn't have the repo publicly available (I don't know why: maybe the user removed himself from github?). The folder in my possession doesn't contain the git info either, therefore I'm left with the code only.

If you contact me by email at ubuntupk@gmail.com, I can send you the code.

BTW, driven by curiosity I searched github for "beep": in the 24 page results, hidden by the entropy, there is also another script of the same kind! Here: https://github.com/edomora97/beep-downloader

**Comment by Jacotsu** [comment]
> Hello @Jacotsu,
> I have good news, I found the code of the CLI script. It was called beepbox. The creator is @poliscript, sadly it doesn't have the repo publicly available (I don't know why: maybe the user removed himself from github?). The folder in my possession doesn't contain the git info either, therefore I'm left with the code only.
> 
> If you contact me by email at [ubuntupk@gmail.com](mailto:ubuntupk@gmail.com), I can send you the code.
> 
> BTW, driven by curiosity I searched github for "beep": in the 24 page results, hidden by the entropy, there is also another script of the same kind! Here: https://github.com/edomora97/beep-downloader

Thank you!
I've read the code of beep-downloader and I've decided to start implementing the beep api ASAP

**Comment by edomora97** [comment]
https://beep.metid.polimi.it/api/jsonws have fun! :stuck_out_tongue_closed_eyes:
