### ISSUE TITLE
JSON Web Services are no longer available

### ISSUE THREAD

**Issue by edomora97** [Jacotsu/polibeepsync#40]
![image](https://user-images.githubusercontent.com/6685454/65707150-3920b980-e08c-11e9-82f9-1037c907194b.png)

Don't know why, but they disabled them :cry:

https://github.com/Jacotsu/polibeepsync/blob/f8dc76b70277a660748da83c59cb9e103c268185/polibeepsync/common.py#L524-L529

**Comment by Jacotsu** [comment]
If they don't reenable them soon enough i'm going to fallback to the web scraping method, but it will break again when they'll release the new beep interface

**Comment by Jacotsu** [comment]
Solved by reinplementing web scraping in Tag 0.5.2
