### ISSUE TITLE
Missing PyQt5 on macOS (pip installation)

### ISSUE THREAD

**Issue by alessionossa** [Jacotsu/polibeepsync#45]
Trying installing the _polibeepsync_ package through _pip_, **PyQt5** is missing and needs to be installed manually on the system.

**Comment by Jacotsu** [comment]
Please, try again with the new mac os app build and report back

**Comment by alessionossa** [comment]
Installing the 0.7.0 release with pip using `pip3 install --ignore-installed polibeepsync`, solved the issue.
