### ISSUE TITLE
Only courses with [YY/YY] are being showed

### ISSUE THREAD

**Issue by malta895** [Jacotsu/polibeepsync#54]
I noticed this strange behavior: only courses starting with academic year between brackets are being showed.
I know there might be some non-courses in the list like "BeeP channel" or "Mobilità internazionale" which don't start with brackets, but in my case I also have some actual courses without academic year in their name that are not being showed in the list.
Could it be fixed, maybe letting the user choose in the settings wether to show or not courses without academic year?

**Comment by Jacotsu** [comment]
> I noticed this strange behavior: only courses starting with academic year between brackets are being showed.
> I know there might be some non-courses in the list like "BeeP channel" or "Mobilità internazionale" which don't start with brackets, but in my case I also have some actual courses without academic year in their name that are not being showed in the list.
> Could it be fixed, maybe letting the user choose in the settings wether to show or not courses without academic year?

Please provide a list of the courses that are not being shown

**Comment by malta895** [comment]
INFORMATICA FORENSE
DIGITAL SYSTEMS DESIGN METHODOLOGIES [FABRIZIO FERRANDI] 
[19-20] Databases 2 [BRAGA]

The latter has brackets but actually it's not shown either (I didn't notice before when making the issue), but it has lowercase letters in the name, while all the shown courses have only uppercase letters in their name, if this can help with the issue.

I also provide the list of non-courses, which are not shown:
BeeP channel
1 - Didattica a distanza - Studenti
CCS - Ingegneria Informatica – Computer Science and Engineering
Mobilità internazionale

**Comment by Jacotsu** [comment]
Added a button to add arbitrary courses as a workaround, it's not ideal but implementing a whitelist would be worse
