### ISSUE TITLE
[Feature Request] Enable maximize button on windows

### ISSUE THREAD

**Issue by zarEclEC** [Jacotsu/polibeepsync#58]

**Comment by Jacotsu** [comment]
It can be easily enabled, but i don't see why it would be useful. As you can see from the screenshots there isn't a big difference between differently sized windows
![image](https://user-images.githubusercontent.com/20172693/93226041-2eff3b80-f773-11ea-9b27-37ff04cef574.png)
![image](https://user-images.githubusercontent.com/20172693/93226070-37577680-f773-11ea-8d28-15c5ebef7898.png)

**Comment by zarEclEC** [comment]
![immagine](https://user-images.githubusercontent.com/6240983/93226381-869da700-f773-11ea-9c75-e45f565cd4c6.png)
Polibeepsync is on but not seen in this image, because the maximize button is disabled

**Comment by Jacotsu** [comment]
> ![immagine](https://user-images.githubusercontent.com/6240983/93226381-869da700-f773-11ea-9c75-e45f565cd4c6.png)
> Polibeepsync is on but not seen in this image, because the maximize button is disabled

oh, I see. Windows tiles only maximizable windows
