### ISSUE TITLE
Empty folder for each course

### ISSUE THREAD

**Issue by rodrprincipe** [Jacotsu/polibeepsync#60]
![image](https://user-images.githubusercontent.com/6618552/94415611-0d904d80-017e-11eb-9f93-10a9a2952d07.png)

I'm running on win10, I've successfully logged and I got each folder for each course but none of those has files inside.
I've also tried installing with pip, but nothing changes.
Can you help me please?

**Comment by Jacotsu** [comment]
This is related to #59, for some reason polibeepsync is not syncing the course data for new users. I'm looking into it

**Comment by ChristianRomeo** [comment]
I had the same problem as @rodrprincipe but changing in utils.py line 28 and 29
from
```
hour = int(rawdate.split(' ')[2].split('.')[0])
minute = int(rawdate.split(' ')[2].split('.')[1])
```
to
```
hour = int(rawdate.split(' ')[2].split(':')[0])
minute = int(rawdate.split(' ')[2].split(':')[1])
```
made it works fine. Hope this helps.

**Comment by Jacotsu** [comment]
> I had the same problem as @rodrprincipe but changing in utils.py line 28 and 29
> from
> 
> ```
> hour = int(rawdate.split(' ')[2].split('.')[0])
> minute = int(rawdate.split(' ')[2].split('.')[1])
> ```
> 
> to
> 
> ```
> hour = int(rawdate.split(' ')[2].split(':')[0])
> minute = int(rawdate.split(' ')[2].split(':')[1])
> ```
> 
> made it works fine. Hope this helps.

nice work, but then courses with the other format wouldn't be downloaded. Anyway the fix is already in master branch, i'm just implementing a proper course database before releasing the new version
