### ISSUE TITLE
Not opening on macOS 10.13.6

### ISSUE THREAD

**Issue by sanchez-rick-c137** [Jacotsu/polibeepsync#61]
The app I downloaded from [this page](https://github.com/Jacotsu/polibeepsync/releases/tag/0.7.2) doesn't open at all. Already tried right-click and Open.

**Comment by sanchez-rick-c137** [comment]
Running the UNIX executable from the inside I get the following output in the terminal:
[Terminal Saved Output.txt](https://github.com/Jacotsu/polibeepsync/files/5298447/Terminal.Saved.Output.txt)

**Comment by Jacotsu** [comment]
Mac os support is best effort at the moment, especially on Catalina due to the notarization "feature". Anyway, have you tried installing it through `pip3 install poliBeePsync`? Make sure that you've installed python3, pip and qt5 beforehand.

**Comment by sanchez-rick-c137** [comment]
It now fires up, seems to be working, but in the terminal I get these errors:

`Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.`

`[ERROR] polibeepsync.qtgui Settings file not found.`

`[ERROR] polibeepsync.qtgui I couldn't find data in the predefined directory. Ignore thismessage if you're using poliBeePsync for the first time.`

Note: they were there even the second time I run the program.

**Comment by sanchez-rick-c137** [comment]
Note: they were there even the second time I run the program.

**Comment by Jacotsu** [comment]
> It now fires up, seems to be working, but in the terminal I get these errors:
> 
> `Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.`
> 
> `[ERROR] polibeepsync.qtgui Settings file not found.`
> 
> `[ERROR] polibeepsync.qtgui I couldn't find data in the predefined directory. Ignore thismessage if you're using poliBeePsync for the first time.`
> 
> Note: they were there even the second time I run the program.

did the settings remain after restarting the program?

**Comment by sanchez-rick-c137** [comment]
Yes, now (it's like the third/fourth time I start the program) I get this output in the terminal

`Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.`
`[INFO] polibeepsync.qtgui Data has been loaded successfully.`
`[INFO] polibeepsync.qtgui User code changed to ********`

I guess it's fine now, but I still don't get why the second time it returned the same error.

**Comment by Jacotsu** [comment]
> Yes, now (it's like the third/fourth time I start the program) I get this output in the terminal
> 
> `Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.`
> `[INFO] polibeepsync.qtgui Data has been loaded successfully.`
> `[INFO] polibeepsync.qtgui User code changed to ********`
> 
> I guess it's fine now, but I still don't get why the second time it returned the same error.

nice, if you have more problems with this i'll reopen the issue
