### ISSUE TITLE
Issue installing polibeepsync on MacOs BigSur

### ISSUE THREAD

**Issue by pippoberto** [Jacotsu/polibeepsync#67]
If I install the app using the .zip file it doesn't open. I installed it with the pip3 command and now the application polibeepsync is in the directory /Users/filippo/Library/Python/3.9/bin but when I execute it doesn't open. If I try to execute " polibeepsync --log-level debug " the command line says " command not found ". What can I do?
Thanks for your support.

**Comment by Jacotsu** [comment]
Unistall both the app package and the pip version, then type the following in the terminal:
- `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
- `brew uninstall qt5`
- `brew install qt`
- `brew install pyside`
- `git clone https://github.com/Jacotsu/polibeepsync.git`
- `pip3.9 install -e polibeepsync`
and then launch with `polibeepsync`

**Comment by pippoberto** [comment]
Thank you, now it works!!
