### ISSUE TITLE
Operations stuck on application update searching

### ISSUE THREAD

**Issue by A-Common-Guy** [Jacotsu/polibeepsync#80]
It's been several weeks the application could not sync because of failing update research. I tried to switch from the .exe application to the build from source approach but nothing changed. I alse tried to downgrade to Python3.7.0 (because most of the problems came up in the same period as python updated on my machine) but it was not a solution

**Comment by Jacotsu** [comment]
post the status log

**Comment by A-Common-Guy** [comment]
The fact was even the status log remained empty After every operation. But so far, i managed right now to solve the problem by deleting all the settings in Local folder. Maybe something broke while switching some versione
